### ISSUE TITLE
Crash when clearing overrides

### ISSUE THREAD

**Issue by paulbartrum** [TradeMe/konfigure#10]
I got a crash when clearing overrides, on this line:

```
configItems.first { it.key == entry.key } to entry.value
```

(The first() method doesn't match any config items.)

Steps to reproduce:

1. Using the config UI override the values of two settings.
2. Delete one of the overridden settings in code.
3. Go back to the config UI (only a single override appears). Tap the clear overrides button.

Expected result:
The overridden setting value(s) are reverted back to their defaults.

Actual result:
Crash.

**Comment by jamiesanson** [comment]
This should be addressed by #11
