### ISSUE TITLE
Support publishing to Maven Central

### ISSUE THREAD

**Issue by jamiesanson** [TradeMe/konfigure#16]
Konfigure is currently published to the now read-only JCenter. There's no deprecation date on this _yet_, however the repository definition in Gradle results in a warning. Ideally, Konfigure would be published to Maven Central. [This article gives a great rundown of what's required.](https://proandroiddev.com/publishing-android-libraries-to-mavencentral-in-2021-8ac9975c3e52)

**Comment by rwjc** [comment]
Thanks Jamie! By chance I'm looking at this as well for something else.
